CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE app_user_roles
(
    app_user_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_app_user_roles PRIMARY KEY (app_user_id, role_id),
    CONSTRAINT fk_app_user_roles_on_user FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_app_user_roles_on_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE session
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token          VARCHAR(255),
    expiring_at    TIMESTAMP WITHOUT TIME ZONE,
    login_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id        BIGINT,
    session_status VARCHAR(255), -- Changed to VARCHAR to store session status as a string
    CONSTRAINT pk_session PRIMARY KEY (id),
    CONSTRAINT fk_session_on_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
